###
POST http://localhost:5000/api/v1/serviciosconsu HTTP/1.1
Content-Type: application/json

{
    "nit":"1111111",
    "nombre":"Minoco",
    "servcios":["ESTUDIOS DE MERCADO", "APOYO A GESTIONES COMERCIALES"],
    "precio": "2.000.000",
    "encargado":"Viviana Restrepo",
    "fecha_auditoria":"9/03/2023",
    "resultado_auditoria":{
        "opinion_limpia":"prueba",
        "opinion_salvedades": "prueba2",
        "opnion_adversa":"prueba3",
        "opnion_denegada":"prueba4"
    }
}